import React from "react";
import Layout from "../Components/Layout";
import Table from "../Components/Table";

const columns = [
    "SKU" ,
    "Product" ,
    "Category" ,
    "Brand" ,
    "Price" ,
    "Unit" ,
    "Qty" ,
   "Created" ,
];

const rows = [
  {
    sku: "PT001",
    product: "Lenovo 3rd Generatio",
    category: "Laptop",
    brand: "Lenovo",
    price: 12500,
    unit: "Pc",
    qty: 100,
    created: "Arroon",
  },
  {
    sku: "PT002",
    product: "Bold V3.2",
    category: "Electronics",
    brand: "Bolt",
    price: 1600,
    unit: "Pc",
    qty: 140,
    created: "Kenneth",
  },
  {
    sku: "PT003",
    product: "Nike Jordan",
    category: "Shoe",
    brand: "Nike",
    price: 6000,
    unit: "Pc",
    qty: 780,
    created: "Gooch",
  },
  {
    sku: "PT004",
    product: "Apple Series 5 Watch",
    category: "Electronics",
    brand: "Apple",
    price: 25000,
    unit: "Pc",
    qty: 450,
    created: "Nathan",
  },
  {
    sku: "PT005",
    product: "Amazon Echo Dot",
    category: "Speaker",
    brand: "Amazon",
    price: 1600,
    unit: "Pc",
    qty: 477,
    created: "Alice",
  },
  {
    sku: "PT006",
    product: "Lobar Handy",
    category: "Furnitures",
    brand: "Woodmart",
    price: 4521,
    unit: "Kg",
    qty: 145,
    created: "Robb",
  },
  {
    sku: "PT007",
    product: "Red Premium Handy",
    category: "Bags",
    brand: "Versace",
    price: 2024,
    unit: "Kg",
    qty: 747,
    created: "Steven",
  },
  {
    sku: "PT008",
    product: "Iphone 14 Pro",
    category: "Phone",
    brand: "Iphone",
    price: 1698,
    unit: "Pc",
    qty: 897,
    created: "Gravely",
  },
  {
    sku: "PT009",
    product: "Black Slim 200",
    category: "Chairs",
    brand: "Bently",
    price: 6794,
    unit: "Pc",
    qty: 741,
    created: "Kevin",
  },
  {
    sku: "PT010",
    product: "Woodcraft Sandal",
    category: "Bags",
    brand: "Woodcraft",
    price: 4547,
    unit: "Kg",
    qty: 148,
    created: "Grillo",
  },
  {
    sku: "PT011",
    product: "Galaxy S23 Ultra",
    category: "Phone",
    brand: "Samsung",
    price: 28999,
    unit: "Pc",
    qty: 550,
    created: "Haris",
  },
  {
    sku: "PT012",
    product: "Dell Inspiron 15",
    category: "Laptop",
    brand: "Dell",
    price: 18000,
    unit: "Pc",
    qty: 88,
    created: "Sohail",
  },
  {
    sku: "PT013",
    product: "Google Nest Mini",
    category: "Speaker",
    brand: "Google",
    price: 2999,
    unit: "Pc",
    qty: 300,
    created: "Ahsan",
  },
  {
    sku: "PT014",
    product: "Xiaomi Mi Band 6",
    category: "Fitness",
    brand: "Xiaomi",
    price: 5999,
    unit: "Pc",
    qty: 900,
    created: "Jibran",
  },
  {
    sku: "PT015",
    product: "AirPods Pro",
    category: "Accessories",
    brand: "Apple",
    price: 19999,
    unit: "Pc",
    qty: 430,
    created: "Tariq",
  },
  {
    sku: "PT016",
    product: "Leather Office Chair",
    category: "Furniture",
    brand: "DecoCraft",
    price: 7500,
    unit: "Pc",
    qty: 120,
    created: "Basit",
  },
  {
    sku: "PT017",
    product: "Casio G-Shock",
    category: "Watches",
    brand: "Casio",
    price: 12000,
    unit: "Pc",
    qty: 280,
    created: "Noman",
  },
  {
    sku: "PT018",
    product: "MacBook Air M2",
    category: "Laptop",
    brand: "Apple",
    price: 280000,
    unit: "Pc",
    qty: 65,
    created: "Sarmad",
  },
  {
    sku: "PT019",
    product: "Smart LED 55in",
    category: "Electronics",
    brand: "Sony",
    price: 110000,
    unit: "Pc",
    qty: 44,
    created: "Fahad",
  },
  {
    sku: "PT020",
    product: "HP DeskJet Printer",
    category: "Office",
    brand: "HP",
    price: 14499,
    unit: "Pc",
    qty: 90,
    created: "Qasim",
  },
];

export default function Category() {
  return (
    <Layout>
      <div className="p-4">
        <Table columns={columns} rows={rows} />
      </div>
    </Layout>
  );
}
